spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/workshop-db
    username: sa
    password: password
    driverClassName: org.h2.Driver

  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always

